---
- name: test https
  hosts: localhost
  connection: local
  gather_facts: false
  become: no

  vars:
    my_url: https://google.com

  tasks:
    - name: curl a url
      ansible.builtin.uri:
        url: "{{ my_url }}"
        ca_path: /etc/pki/tls/certs/ca-bundle.crt
      register: result

    - name: debug result
      debug:
        var: result

