---
- name: test https
  hosts: localhost
  connection: local
  gather_facts: false
  become: no

  vars:
    my_url: https://google.com
    ca_pathy: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
  tasks:
    - name: test with URI module 
      ansible.builtin.uri:
        url: "{{ my_url }}"
        ca_path: "{{ ca_pathy }}"
      register: result

    - name: debug result
      debug:
        var: result
